[package]
name = "Tamriel_Data"
version = "10.1"
description = "The data repository for Tamriel Rebuilt, Project Tamriel and Padomic Isles province mods."
homepage = "https://www.nexusmods.com/morrowind/mods/44537"
repository = "https://github.com/TD-Addon/TD_Addon"
authors = [
	"chef",
	"Kynesifnar",
	"Evil Eye",
	"Alyst3r",
	"Jackimoff Wackimoff",
	"Rats",
	"Melchior Dahrk",
	"Dillon",
	"MwGek",
	"SACarrow",
]

[dependencies.mwse]
buildnumber = 3074

[tools.csse]
deprecated = [
	"T_De_ToyGuar_01",
	"T_De_SetRed_X_Skar_01",
	"T_De_BonemoldKragen_Helm_01",
	"T_Com_SetHarbor_FishBeheaded_01",
	"T_Com_SetHarbor_FishBeheaded_02",
	"TR_hla_canyon_guard",
	"TR_hla_canyon_guard_f",
	"TR_hla_canyon_guard_f_s",
	"TR_hla_canyon_guard_s",
	"TR_hla_canyon_shooter",
	"TR_hla_guard",
	"TR_hla_guard_f",
	"TR_hla_guard_s",
	"TR_hla_kragen_guard",
	"TR_hla_kragen_guard_f",
	"TR_hla_kragen_guard_f_s",
	"TR_hla_kragen_guard_s",
	"TR_hla_kragen_shooter",
	"TR_hla_sharpshooter",
	"TR_imp_archer",
	"TR_imp_archer_b",
	"TR_imp_archer_s",
	"TR_imp_guard",
	"TR_imp_guard_cap",
	"TR_imp_guard_cap_s",
	"TR_imp_guard_s",
	"TR_ind_guard",
	"TR_ind_guard_f",
	"TR_ind_guard_f_s",
	"TR_ind_guard_s",
	"TR_ind_ulvra_guard",
	"TR_ind_ulvra_guard_f",
	"TR_ind_ulvra_guard_f_s",
	"TR_ind_ulvra_guard_s",
	"TR_ordinator",
	"TR_ordinator_high",
	"TR_ordinator_high_s",
	"TR_ordinator_s",
	"TR_ordinator_war",
	"TR_ordinator_war_s",
	"TR_red_guard",
	"TR_red_guard_b",
	"TR_red_guard_f",
	"TR_red_guard_f_s",
	"TR_red_guard_s",
	"TR_red_guard_strong",
	"TR_red_guard_strong_f",
	"TR_red_stone_guard",
	"TR_red_stone_guard_f",
	"TR_red_stone_guard_f_s",
	"TR_red_stone_guard_s",
	"TR_red_watchman",
	"TR_red_watchman_b",
	"TR_red_watchman_f",
	"TR_red_watchman_s",
	"TR_telv_guard",
	"TR_telv_guard_s",
	"TR_telvanni guard_02",
	"TR_telvanni guard_02_s",
	"T_Mw_Flora_RedCoral01",
	"T_Mw_Flora_RedCoral02",
	"T_Mw_Flora_RedCoral03",
	"T_De_ToyGuar_01",
	"T_Tsa_F_Urn_01",
	"T_Tsa_F_Urn_02",
	"T_Yne_Drink_Pudjing",
	"T_Pi_FloraYn_FlowerY_01",
	"T_Pi_FloraYn_FlowerY_02",
	"T_Pi_FloraYn_FlowerY_03",
	"T_Mw_FloraCM_Maiden03",
	"T_Mw_FloraCM_Maiden04",
	"T_Mw_FloraCM_Maiden05",
	"T_Mw_FloraCM_Maiden06",
	"T_Mw_Fau_Eyest_01",
	"T_Mw_Fau_EyestDs_01",
	"T_Mw_Fauna_Riverstrider_01",
]